### ISSUE TITLE
TODO for rsync distribution

### ISSUE THREAD

**Issue by mguentner** [NixIPFS/infrastructure#3]
* [ ] add mirrorbits config and module -> @fpletz 
* [ ] redis sentinel config and modules for mirrorbits
* [ ] figure out how to make acme challenges available to all nodes (distributed filesystem)?
